# Generated by Django 4.2 on 2023-04-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ResumeBuilder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=500, null=True)),
                ("last_name", models.CharField(blank=True, max_length=500, null=True)),
                ("jobtitle", models.CharField(blank=True, max_length=500, null=True)),
                ("email", models.CharField(blank=True, max_length=500, null=True)),
                ("phone", models.CharField(blank=True, max_length=500, null=True)),
                ("github", models.CharField(blank=True, max_length=500, null=True)),
                ("linkedin", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="Resume Image"),
                ),
                (
                    "positiontitle1",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("employer", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "positioncity",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "positionyear",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "positionmonth",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("todayyear", models.CharField(blank=True, max_length=500, null=True)),
                ("todaymonth", models.CharField(blank=True, max_length=500, null=True)),
                ("todayfdsaf", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "degreefield",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("degree", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "degreeschoolname",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "degreeschoolcity",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "degreeschoolyear",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "degreeschoolmonth",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "degreeschooltoyear",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "degreeschooltomonth",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("hscfield", models.CharField(blank=True, max_length=500, null=True)),
                ("hscdegree", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "hscdegreeschoolname",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "hscdegreeschoolcity",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "hscdegreeschoolyear",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "hscdegreeschoolmonth",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "hscdegreeschooltoyear",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "hscdegreeschooltomonth",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("skills", models.CharField(blank=True, max_length=500, null=True)),
                ("footer", models.CharField(blank=True, max_length=500, null=True)),
                ("hobby", models.CharField(blank=True, max_length=500, null=True)),
                ("language", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "certificate",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "certificateyear",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "certificatemonth",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "certificate1",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "certificateyear1",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "certificatemonth1",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "certificate2",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "certificateyear2",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "certificatemonth2",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
            ],
        ),
    ]
