# Generated by Django 4.2 on 2023-04-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_resumebuilder_user_alter_resumebuilder_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resumebuilder",
            name="image",
            field=models.ImageField(
                default="default/default.png", upload_to="Resume Image"
            ),
        ),
    ]
