# Generated by Django 4.2 on 2023-04-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_resumebuilder_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="resumebuilder",
            name="aboutme",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="resumebuilder",
            name="image",
            field=models.ImageField(default="default.png", upload_to="Resume Image"),
        ),
    ]
